// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADyNLcRpBW35rvyAaFkywIQ7j4-JhII-0',
    appId: '1:375309969941:web:52b348d053c7e59a01fc1c',
    messagingSenderId: '375309969941',
    projectId: 'flutter-chat-app-ac8b1',
    authDomain: 'flutter-chat-app-ac8b1.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ac8b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ5P6H96CkTXLxfLqP6mZDXCI8rSy65EY',
    appId: '1:375309969941:android:eed34bf7eff1256601fc1c',
    messagingSenderId: '375309969941',
    projectId: 'flutter-chat-app-ac8b1',
    storageBucket: 'flutter-chat-app-ac8b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArXQkeRe5d3jwDRI8gv23lZAZi7ctcAYU',
    appId: '1:375309969941:ios:6c490e54b67180d801fc1c',
    messagingSenderId: '375309969941',
    projectId: 'flutter-chat-app-ac8b1',
    storageBucket: 'flutter-chat-app-ac8b1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArXQkeRe5d3jwDRI8gv23lZAZi7ctcAYU',
    appId: '1:375309969941:ios:6c490e54b67180d801fc1c',
    messagingSenderId: '375309969941',
    projectId: 'flutter-chat-app-ac8b1',
    storageBucket: 'flutter-chat-app-ac8b1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADyNLcRpBW35rvyAaFkywIQ7j4-JhII-0',
    appId: '1:375309969941:web:ce65348161dec9b301fc1c',
    messagingSenderId: '375309969941',
    projectId: 'flutter-chat-app-ac8b1',
    authDomain: 'flutter-chat-app-ac8b1.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ac8b1.appspot.com',
  );

}